services:
  myblog:
    build: .
    ports:
      - "5000:5000"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - sqlserver
    volumes:
      - ./wwwroot/images:/app/wwwroot/images

  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      MSSQL_SA_PASSWORD: "**REMOVED**"
      ACCEPT_EULA: "Y"
